// Automatically generated by astro-icon
// 6a5b13576e63878a7b69f0ff8dad17748e8389ca84bdaf95fe11c3fd33a92788

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "football"
		| "instagram"
		| "linkedin";
}