// Automatically generated by astro-icon
// c25f7906311e3e95e99305d7f029699aedb1cb5225c9059a979aacc52dbd3e34

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "football"
		| "instagram"
		| "linkedin"
		| "news"
		| "wave";
}